### ISSUE TITLE
Is there a better way to load @font-face files from css using url()?

### ISSUE THREAD

**Issue by ihealthdavid** [thereactivestack/meteor-webpack#209]
Hi, great project. Is there a better way to load ```@font-face``` files from css using url()?

I couldn't get the relative path working in css-loader using this package for ```@font-face``` url(), so I had to do the following:

1) modify assets/webpack.config.js to get a consistent url, not the hashed url:

> ie) http://localhost:3500/assets/public/fonts/web-mob.eot instead of http://localhost:3500/assets/3fd71036a64d191399bdf9b767da603a.eot

```js
{ test: /\.svg$/, loader: 'url?limit=65000&mimetype=image/svg+xml&name=public/fonts/[name].[ext]' },
{ test: /\.woff$/, loader: 'url?limit=65000&mimetype=application/font-woff&name=public/fonts/[name].[ext]' },
{ test: /\.woff2$/, loader: 'url?limit=65000&mimetype=application/font-woff2&name=public/fonts/[name].[ext]' },
{ test: /\.[ot]tf$/, loader: 'url?limit=65000&mimetype=application/octet-stream&name=public/fonts/[name].[ext]' },
{ test: /\.eot$/, loader: 'url?limit=65000&mimetype=application/vnd.ms-fontobject&name=public/fonts/[name].[ext]' }
```
* The file sizes are over 65k, so it would have been using file-loader instead of url-loader

2) use absolute url in my css for the font files
>(Meteor server is still running on localhost:3000)

```css
@font-face {
  font-family: "web-mob";
  src: url('http://localhost:3500/assets/public/fonts/web-mob.eot');
  src: url('http://localhost:3500/assets/public/fonts/web-mob.eot?#iefix') format('embedded-opentype'),
       url('http://localhost:3500/assets/public/fonts/web-mob.woff2') format('woff2'),
       url('http://localhost:3500/assets/public/fonts/web-mob.woff') format('woff'),
       url('http://localhost:3500/assets/public/fonts/web-mob.ttf') format('truetype'),
       url('http://localhost:3500/assets/public/fonts/web-mob.svg#web-mob') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

I tried to follow this guide, but the css could not find the files until I used absolute paths as above.
https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/

I'd appreciate any tips. Thanks!
